site_name: Nocalhost Docs
theme:
  name: material
  custom_dir: .

nav:
  - Getting started: getting-started.md
  - Installation: installation.md
  - Concepts: 
    - Cluster: cluster.md
    - Application: application.md
    - User: user.md
    - Service: service.md
    - DevSpace: devspace.md
    - DevContainer: devcontainer.md
  - Tutorials:
    - Docker: Tutorials/nocalhost-with-docker-desktop.md
    - Helm: Tutorials/nocalhost-with-helm.md
    - Kubernetes: Tutorials/nocalhost-with-k8s-manifests.md
    - MiniKube: Tutorials/nocalhost-with-minikube.md
    - TKE: Tutorials/nocalhost-with-tke.md
    - Serverless Kubernetes: Tutorials/nocalhost-with-serverless-kubernetes.md
    - CLI: Tutorials/nocalhost-without-ide-plugin.md
  - References:
    - Architecture : architecture.md
    - Config Specs: References/nocalhost-config-yaml-spec.md
    - CLI Commands: cli-commands.md
    - File sync: file-sync.md
    - Service Dependency: service-denepdency.md
  - FAQ: faq.md
