site_name: Nocalhost Docs
theme:
  name: material
  custom_dir: overrides
  logo: assets/images/favicon.ico
  favicon: assets/images/favicon.ico
  palette:
    - scheme: nocalhost

extra_css:
  - stylesheets/extra.css
  - stylesheets/home.css
  - stylesheets/grid.css

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols


nav:
  - 中文文档:
    - 快速上手: zh/getting-started.md
    - 概念介绍:
      - Cluster: zh/Concepts/cluster.md
      - Application: zh/Concepts/application.md
      - User: zh/Concepts/user.md
      - Service: zh/Concepts/service.md
      - DevMode: zh/Concepts/devmode.md
      - DevSpace: zh/Concepts/devspace.md
      - DevContainer: zh/Concepts/devcontainer.md
    - 使用教程:
      - Manifest 应用: zh/Tutorials/nocalhost-with-k8s-manifests.md
      - Helm Chart 应用: zh/Tutorials/nocalhost-with-helm.md
    - 参考手册:
      - Nocalhost 配置说明: zh/References/nocalhost-config-yaml-spec.md
      - Nocalhost 架构: zh/References/architecture.md
      - Nhctl CLI: zh/References/cli-commands.md
    - 常见问题:
      - Helm 工作负载名称: zh/FAQ/work-with-helm.md
      - 依赖标签选择器: zh/FAQ/dep-label-selector.md
      - HPA 控制的 Deployment: zh/FAQ/deployment-with-hpa.md
      - 多容器 Pod: zh/FAQ/multi-container-pods.md
      - VSCode 插件功能限制: zh/FAQ/vscode-plugin-limits.md
      - 加密的 SSH 私钥: zh/FAQ/ssh-private-keys-passphrase.md
      - 默认管理账户: zh/FAQ/default-account.md
  - Getting started: getting-started.md
  - Installation: installation.md
  - Deployment: deployment.md
  - Concepts:
    - Cluster: Concepts/cluster.md
    - Application: Concepts/application.md
    - User: Concepts/user.md
    - Service: Concepts/service.md
    - DevSpace: Concepts/devspace.md
    - DevContainer: Concepts/devcontainer.md
    - DevMode: Concepts/devmode.md
  - Tutorials:
    - Docker: Tutorials/nocalhost-with-docker-desktop.md
    - Helm: Tutorials/nocalhost-with-helm.md
    - Kubernetes: Tutorials/nocalhost-with-k8s-manifests.md
    - MiniKube: Tutorials/nocalhost-with-minikube.md
    - TKE: Tutorials/nocalhost-with-tke.md
    - Serverless Kubernetes: Tutorials/nocalhost-with-serverless-kubernetes.md
    - CLI: Tutorials/nocalhost-without-ide-plugin.md
    - VScode Plugin: Tutorials/vscode-plugin.md
  - References:
    - Architecture : References/architecture.md
    - Config Specs: References/nocalhost-config-yaml-spec.md
    - CLI Commands: References/cli-commands.md
    - File sync: References/file-sync.md
    - Service Dependency: References/service-dependency.md
    - Port Forward: References/port-forward.md
  - FAQ:
    - Work with Helm: FAQ/work-with-helm.md
    - Dependency Label Selector: FAQ/dep-label-Selector.md
    - Deployment with HPA: FAQ/deployment-with-hpa.md
    - Multi-container Pods: FAQ/multi-container-pods.md
    - VSCode Plugin Limits: FAQ/vscode-plugin-limits.md
    - SSH Private Keys Passphrase: FAQ/ssh-private-keys-passphrase.md
    - Default admin account: FAQ/default-account.md
